### ISSUE TITLE
Caso d'uso prepara birra

### ISSUE THREAD

**Issue by Elsacred02** [UnimibSoftEngCourse2022/homebrew-ferioli-pinciroli-trolli-spinelli-boolean-rhapsody#23]
- [x] Creare classe Birra
- [x] creare Dao Birra
- [x] creare repository birra
- [x] viewmodel per gestire birre

**Comment by Pynci** [comment]
Io e @Elsacred02 iniziamo ad occuparci del livello basso, andando ad esporre le API necessarie per effettuare le operazioni CRUD
