### ISSUE TITLE
Modifica al diagramma delle classi di progetto

### ISSUE THREAD

**Issue by Pynci** [UnimibSoftEngCourse2022/homebrew-ferioli-pinciroli-trolli-spinelli-boolean-rhapsody#4]
Sistemare le classi Attrezzo e Ingrediente nel diagramma delle classi di progetto.
È necessario modellare non solo l'ingrediente/attrezzo, ma anche l'istanza dell'ingrediente/attrezzo: l'istanza deve contenere informazioni relative all'effettiva disponibilità attuale di un dato ingrediente o attrezzo.

**Comment by Elsacred02** [comment]
Aggiungere i riferimenti tra i result ed i model utilizzati
