### ISSUE TITLE
Cosa devo preparare oggi

### ISSUE THREAD

**Issue by Pynci** [UnimibSoftEngCourse2022/homebrew-ferioli-pinciroli-trolli-spinelli-boolean-rhapsody#43]
Utilizzare gli algoritmi di ottimizzazione progettati in precedenza per implementare la funzionalità "cosa devo preparare oggi": è necessario decidere l'approccio da seguire.

La traccia recita:
> A special characteristic of the application is the "what should I
brew today?" feature: it goes through the recipes, and taking into account the available ingredients
and brewing capacity of the equipment selects a recipe that can be brewed with the available
ingredients, maximizing the use of the ingredients, and the batch size.

E poi ancora:
> Brew Day! must support a useful feature for brewers: "what should I brew today?" goes through the recipes database,
and chooses the recipe that maximizes the use of the available ingredients, taking into account the
equipment capacity, of course.

Sebbene la scelta più logica sia quella di selezionare la ricetta in grado di dare origine al maggior numero di litri di birra con il minor numero di ingredienti utilizzati, questo potrebbe non essere quanto richiesto: nella traccia infatti si evince (dato che lo ripete due volte) che la priorità deve essere la massimizzazione del consumo di ingredienti e, secondariamente, il numero di litri di birra prodotti.

L'algoritmo di ottimizzazione degli attrezzi dovrebbe comunque essere corretto e riutilizzabile, forse bisogna mettere mano a quello degli ingredienti.

**Comment by Elsacred02** [comment]
Poichè entrambi gli algoritmi restituiscono la ricetta scelta con la quantità di litri che si possono produrre, potremmo considerare l'idea di applicare il pattern strategy per ridurre il numero di metodi della classe GestioneBirraDomain

**Comment by Pynci** [comment]
Butto un occhio al codice e vedo cosa si può fare

**Comment by Pynci** [comment]
Funziona tutto, manca da correggere il bug sul backstack
