### ISSUE TITLE
GestisciAttrezzo

### ISSUE THREAD

**Issue by Elsacred02** [UnimibSoftEngCourse2022/homebrew-ferioli-pinciroli-trolli-spinelli-boolean-rhapsody#5]
Implementare caso d'uso GestisciAttrezzo:

- [x] Model Attrezzo
- [x] Dao Attrezzo
- [x] Classe Result
- [x] repositoryAttrezzo
- [x] Viewmodel per fragment Attrezzo
- [x] Grafica fragment

**Comment by Pynci** [comment]
Sto iniziando a scrivere i casi di test: per farli in maniera agevole ho trovato un framework utile che permette di fare il mocking di classi che hanno dipendenze; si chiama [Mockito](https://site.mockito.org/).
Includo le sue dipendenze nel file Gradle e provo ad utilizzarlo, potrebbe farci risparmiare un bel po' di tempo (stasera mi metto a guardare un tutorial indiano per vedere bene come funziona).
